// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Y8feO7goEtRILJyD7yh9XN2bm_EBoF4',
    appId: '1:158353651081:web:27a07f5c2f523eb7199d58',
    messagingSenderId: '158353651081',
    projectId: 'e-commerce-app-3fccc',
    authDomain: 'e-commerce-app-3fccc.firebaseapp.com',
    storageBucket: 'e-commerce-app-3fccc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZctjyuriQJ85GI5m1_ujXCfLXPkFLZU',
    appId: '1:158353651081:android:c0df66dbd3c72f44199d58',
    messagingSenderId: '158353651081',
    projectId: 'e-commerce-app-3fccc',
    storageBucket: 'e-commerce-app-3fccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAjiB_o3Kx_mV-jBjV0nJmUqqLihsGdfI',
    appId: '1:158353651081:ios:925e9d172b8302a5199d58',
    messagingSenderId: '158353651081',
    projectId: 'e-commerce-app-3fccc',
    storageBucket: 'e-commerce-app-3fccc.appspot.com',
    androidClientId: '158353651081-g98vrse5sm8lh1i21oepf99agtrd177q.apps.googleusercontent.com',
    iosClientId: '158353651081-rfgqcfs7jnsu70ipuu5lqf57h9b34com.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
